[server]
headless = true
address = "0.0.0.0"
port = 8501
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[theme]
base = "dark"
primaryColor = "#38bdf8"
backgroundColor = "#0b0f19"
secondaryBackgroundColor = "#1e293b"
textColor = "#f8fafc"
font = "sans serif"